/**
 * Dados das salas e das aulas da semana (quantidade definida pelo professor).
 * Em produção, substituir por resposta da API.
 */
export const cursos = [
  {
    id: 1,
    titulo: 'Primeiros Passos no Digital',
    nivel: 'Iniciante',
    progresso: 100,
    cor: '#FFD700',
    icone: '🌻',
    videoId: 'dQw4w9WgXcQ',
    descricao:
      'Aprenda os fundamentos do mundo digital e dê seus primeiros passos com segurança.',
    aulasSemana: [
      {
        id: 1,
        titulo: 'Boas-vindas e ambiente digital',
        dataLancamento: '2026-05-05',
        liberado: true,
        videoId: 'dQw4w9WgXcQ',
        descricao: 'Visão geral do curso e primeiros conceitos.',
        progresso: 100,
      },
      {
        id: 2,
        titulo: 'Navegação segura na web',
        dataLancamento: '2026-05-07',
        liberado: true,
        videoId: 'dQw4w9WgXcQ',
        descricao: 'Como identificar sites confiáveis e evitar riscos.',
        progresso: 80,
      },
      {
        id: 3,
        titulo: 'Projeto prático da semana',
        dataLancamento: '2026-05-10',
        liberado: true,
        videoId: 'dQw4w9WgXcQ',
        descricao: 'Colocando em prática o que você aprendeu.',
        progresso: 40,
      },
    ],
  },
  {
    id: 2,
    titulo: 'Vendendo no WhatsApp',
    nivel: 'Intermediário',
    progresso: 45,
    cor: '#25D366',
    icone: '📱',
    videoId: 'dQw4w9WgXcQ',
    descricao: 'Aprenda a transformar conversas em vendas reais usando o WhatsApp Business.',
    aulasSemana: [
      {
        id: 1,
        titulo: 'Perfil comercial e catálogo',
        dataLancamento: '2026-05-04',
        liberado: true,
        videoId: 'dQw4w9WgXcQ',
        descricao: 'Configure seu negócio no WhatsApp Business.',
        progresso: 100,
      },
      {
        id: 2,
        titulo: 'Scripts de atendimento',
        dataLancamento: '2026-05-08',
        liberado: true,
        videoId: 'dQw4w9WgXcQ',
        descricao: 'Mensagens que convertem sem parecer robóticas.',
        progresso: 45,
      },
      {
        id: 3,
        titulo: 'Automações e listas de transmissão',
        dataLancamento: '2026-05-12',
        liberado: false,
        videoId: 'dQw4w9WgXcQ',
        descricao: 'Próximo módulo: use com moderação e ética.',
        progresso: 0,
      },
      {
        id: 4,
        titulo: 'Métricas e acompanhamento',
        dataLancamento: '2026-05-14',
        liberado: false,
        videoId: 'dQw4w9WgXcQ',
        descricao: 'A ser liberado pelo professor.',
        progresso: 0,
      },
    ],
  },
  {
    id: 3,
    titulo: 'Instagram para Negócios',
    nivel: 'Avançado',
    progresso: 10,
    cor: '#C13584',
    icone: '📸',
    videoId: 'dQw4w9WgXcQ',
    descricao: 'Domine o Instagram e transforme seu perfil em uma vitrine profissional.',
    aulasSemana: [
      {
        id: 1,
        titulo: 'Bio, destaques e posicionamento',
        dataLancamento: '2026-05-03',
        liberado: true,
        videoId: 'dQw4w9WgXcQ',
        descricao: 'Primeira impressão que vende.',
        progresso: 100,
      },
      {
        id: 2,
        titulo: 'Conteúdo estratégico (Reels e Stories)',
        dataLancamento: '2026-05-09',
        liberado: false,
        videoId: 'dQw4w9WgXcQ',
        descricao: 'Planejamento editorial — liberação em breve.',
        progresso: 0,
      },
    ],
  },
  {
    id: 4,
    titulo: 'Segurança na Internet',
    nivel: 'Essencial',
    progresso: 0,
    cor: '#2A52BE',
    icone: '🛡️',
    videoId: 'dQw4w9WgXcQ',
    descricao: 'Proteja seus dados, senhas e navegue com total segurança na rede.',
    aulasSemana: [
      {
        id: 1,
        titulo: 'Senhas e autenticação',
        dataLancamento: '2026-05-06',
        liberado: true,
        videoId: 'dQw4w9WgXcQ',
        descricao: 'Boas práticas e gerenciadores de senha.',
        progresso: 0,
      },
      {
        id: 2,
        titulo: 'Phishing e golpes comuns',
        dataLancamento: '2026-05-11',
        liberado: true,
        videoId: 'dQw4w9WgXcQ',
        descricao: 'Reconheça armadilhas antes de clicar.',
        progresso: 0,
      },
      {
        id: 3,
        titulo: 'Privacidade em redes sociais',
        dataLancamento: '2026-05-13',
        liberado: false,
        videoId: 'dQw4w9WgXcQ',
        descricao: 'Em breve.',
        progresso: 0,
      },
      {
        id: 4,
        titulo: 'Backup e recuperação',
        dataLancamento: '2026-05-15',
        liberado: false,
        videoId: 'dQw4w9WgXcQ',
        descricao: 'Em breve.',
        progresso: 0,
      },
      {
        id: 5,
        titulo: 'Checklist de segurança',
        dataLancamento: '2026-05-16',
        liberado: false,
        videoId: 'dQw4w9WgXcQ',
        descricao: 'Em breve.',
        progresso: 0,
      },
    ],
  },
  {
    id: 5,
    titulo: 'Criando Artes no Canva',
    nivel: 'Criativo',
    progresso: 0,
    cor: '#00C4CC',
    icone: '🎨',
    videoId: 'dQw4w9WgXcQ',
    descricao: 'Crie artes incríveis e profissionais para suas redes sociais de forma simples.',
    aulasSemana: [
      {
        id: 1,
        titulo: 'Interface e primeiros layouts',
        dataLancamento: '2026-05-02',
        liberado: true,
        videoId: 'dQw4w9WgXcQ',
        descricao: 'Tour pelo Canva e templates.',
        progresso: 0,
      },
    ],
  },
  {
    id: 6,
    titulo: 'Controle Financeiro Simples',
    nivel: 'Básico',
    progresso: 0,
    cor: '#85bb65',
    icone: '💰',
    videoId: 'dQw4w9WgXcQ',
    descricao: 'Organize as finanças do seu negócio de maneira prática e sem complicações.',
    aulasSemana: [
      {
        id: 1,
        titulo: 'Caixa do dia a dia',
        dataLancamento: '2026-05-01',
        liberado: true,
        videoId: 'dQw4w9WgXcQ',
        descricao: 'Entradas e saídas sem complicação.',
        progresso: 0,
      },
      {
        id: 2,
        titulo: 'Precificação simples',
        dataLancamento: '2026-05-04',
        liberado: true,
        videoId: 'dQw4w9WgXcQ',
        descricao: 'Cálculo de preço mínimo e margem.',
        progresso: 0,
      },
      {
        id: 3,
        titulo: 'Reserva de emergência',
        dataLancamento: '2026-05-08',
        liberado: false,
        videoId: 'dQw4w9WgXcQ',
        descricao: 'Aguardando liberação.',
        progresso: 0,
      },
    ],
  },
]

export function getCursoById(salaId) {
  const id = Number(salaId)
  return cursos.find((c) => c.id === id) || null
}
